import NavBar from "@/components/NavBar";
import { gql, useQuery } from "@apollo/client";
import Head from "next/head";
import { useState } from "react";
import { useRouter } from 'next/router';


const GET_PROFILE = gql`
  query Profile($handle: Handle) {
    profile(request: { handle: $handle }) {
      id
      name
      bio
    }
  }
`;

type Profile = {
  bio: string;
  id: string;
  name: string;
};

export default function Home() {
  const [handle, setHandle] = useState("");
  const [profile, setProfile] = useState<Profile>();
  const { loading, error, data, refetch } = useQuery(GET_PROFILE, {
    variables: { handle },
  });
  let router = useRouter()


  const changeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    setHandle(e.target.value);
  };

  const getProfile = async (e: React.FormEvent) => {
    e.preventDefault();
    refetch();
    setProfile(data.profile);
  };

  function handlePayment() {
    router.push('./profile/index2') 
    console.log('This is Dev_Danny on the back-end')
}
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto container p-5 relative">
        <NavBar />
        <main className="mt-6 lg:mt-20 md:w-[640px] mx-auto">
          <section className="flex flex-col items-center justify-center">
            <h1 className="text-[3rem] md:text-[6rem] italic">Capital Frens</h1>
            <p className="text-[1rem] md:text-[2rem] text-center w-[21rem]">
              Turn your social capital into financial $CAPITAL
            </p>
            <div className="flex flex-col gap-4 mt-5">
              <button  className="bg-[red] text-[#d2d242] px-6 py-3 text-xs lg:text-base">
                Lets do it
              </button>
              <button className="bg-[red] text-[#d2d242] px-6 py-3 text-xs lg:text-base">
                Buy $CAPITAL
              </button>
            </div>
          </section>

          <section className="flex flex-col items-center mt-16">
            <p className="text-[1rem] md:text-[1.5rem] mb-2" id="lens-input">
              Input your lens Handle
            </p>
            <form onSubmit={getProfile}>
              <input
                type="text"
                className="w-[100%] mb-4 p-2"
                id="input-field"
                onChange={changeHandler}
                value={handle}
              />
              <div className="w-[100%] flex justify-center">
                <button
                  type="submit"
                  onClick={handlePayment}
                  className="text-[#000]font-medium bg-[#37c9a5] px-10 py-2 rounded-xl text-xs lg:text-base justify-center"
                >
                  submit
                </button>
              </div>
            </form>
          </section>

          {profile && (
            <section className="mt-10 mb-10 flex justify-center px-2 md:px-0">
              <div className="flex flex-col items-center justify-center md:w-1/2 rounded-md p-10 mt-4 shadow-lg bg-white">
                <p>ID - {profile.id}</p>
                <h2 className="text-2xl font-semibold mt-4">
                         <span className="font-semibold">NAME</span> -{" "}
                  {profile.name}
                </h2>
                <p className="mt-4">
                     
                  <span className="font-semibold">BIO</span> - {profile.bio}
                </p>
              </div>
            </section>
          )}
        </main>
      </div>
    </>
  );
}
